basePath: /
definitions:
  models.User:
    properties:
      birthdate:
        type: string
      document:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: fbazmitsuishi@gmail.com
  description: This is a sample bank api
  title: Bank API
  version: 0.0.1
paths:
  /user:
    get:
      description: function to list all users in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Get Users
      tags:
      - users
    post:
      description: function to create a new user in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Create User
      tags:
      - users
swagger: "2.0"
